{% set name = "redis-semaphore" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/Redis-Semaphore-{{ version }}.tar.gz
  sha256: c3ce7113fda317692c27ed704e3da41444f1c004d5bd19a0aaa56adfda5bbaec

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - redis-py  # named redis on PyPI and redis-py on conda-forge; importable as 'redis'

test:
  imports:
    - redis_semaphore
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bluele/redis-semaphore
  summary: A distributed semaphore and mutex built on Redis.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
